### ISSUE TITLE
Teacher Details Page

### ISSUE THREAD

**Issue by manusmd** [manusmd/mystudy#10]
# Story
As a user
I want to click on a teacher to see the details like name, address, telephone, group(s) and subject(s) of the student.

# Design
![image](https://user-images.githubusercontent.com/89474622/142999500-a5c8ed3d-2889-4369-b54f-d08cfae662eb.png)

# Components to create
_!!! Brackets contain the props !!!_

*Same components as Student Details page*

# Tasks

- [x] Add page title
- [ ] Add mapElement
- [x] Add studentTeacherForm
- [ ] Add Cancel Button
- [ ] Add Save Button
