### ISSUE TITLE
Group Details page

### ISSUE THREAD

**Issue by manusmd** [manusmd/mystudy#11]
# Story
As a user
I want to click on a group to see the details like groupname, students and teachers.

# Design
![image](https://user-images.githubusercontent.com/89474622/143003066-6a83e3eb-aaf4-4d57-b3fa-737daa788d5d.png)

# Components to create
_!!! Brackets contain the props !!!_

- [ ] groupSubjectForm(groupName, students[], teachers[])

# Tasks

- [ ] Add page title
- [ ] Add group picture
- [ ] Add groupSubjectForm
- [ ] Add Cancel Button
- [ ] Add Save Button

**Comment by manusmd** [comment]
Closed cause it's not necessary for project
