### ISSUE TITLE
Subject Details page

### ISSUE THREAD

**Issue by manusmd** [manusmd/mystudy#12]
# Story
As a user
I want to click on a subject to see the details like subject, students and teachers.

# Design
![image](https://user-images.githubusercontent.com/89474622/143004069-b9f1e5a9-066d-4ccd-9240-6573aaa25f2f.png)

# Components to create
_!!! Brackets contain the props !!!_

*Same components as group details page but without the image*

# Tasks

- [ ] Add page title
- [ ] Add groupSubjectForm
- [ ] Add Cancel Button
- [ ] Add Save Button

**Comment by manusmd** [comment]
Closed cause it's not necessary for project
