### ISSUE TITLE
Add Student page

### ISSUE THREAD

**Issue by manusmd** [manusmd/mystudy#14]
# Story
As a user
I want to add students with attributes like surname, last name, address, telephone, groups, subjects.

# Design
![image](https://user-images.githubusercontent.com/89474622/143005422-41053412-c28e-4b84-ab19-318555987a77.png)

# Components to create
_!!! Brackets contain the props !!!_

*Same components as Student Details page*

# Tasks
- [ ] Add page title
- [ ] Add studentTeacherForm
- [ ] Add Cancel Button
- [ ] Add Save Button
