### ISSUE TITLE
Add Teacher page

### ISSUE THREAD

**Issue by manusmd** [manusmd/mystudy#15]
# Story
As a user
I want to add teachers with attributes like surname, last name, address, telephone, groups, subjects.

# Design
![image](https://user-images.githubusercontent.com/89474622/143006412-b6962a4c-79f1-41eb-97b8-117a622667d6.png)

# Components to create
_!!! Brackets contain the props !!!_

*Same components as Teacher Details page*

# Tasks
- [ ] Add page title
- [ ] Add studentTeacherForm
- [ ] Add Cancel Button
- [ ] Add Save Button
