### ISSUE TITLE
Add Group page

### ISSUE THREAD

**Issue by manusmd** [manusmd/mystudy#16]
# Story
As a user
I want to add groups with attributes like groupname, students and teachers.

# Design
![image](https://user-images.githubusercontent.com/89474622/143007152-7416bc9f-d071-4c67-b77a-7658eb17d4ea.png)

# Components to create
_!!! Brackets contain the props !!!_

- [ ] uploadImage(file)

# Tasks
- [ ] Add page title
- [ ] Add uploadImage
- [ ] Add groupSubjectForm
- [ ] Add Cancel Button
- [ ] Add Save Button
