### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by manusmd** [manusmd/mystudy#3]
# Story
As a user
I want to login to my account via username and password.

# Design
![image](https://user-images.githubusercontent.com/89474622/142891017-590d30fc-fab3-4e67-aa95-81b1b36d6ccf.png)

# Components to create
_!!! Brackets contain the props !!!_
- [x] Input field (size, placeholder, input type)
- [x] button component (placeolder, type)

# Tasks
- [x] Add page title
- [x] Add logo
- [x] Add username input
- [x] Add password input
- [x] Add login button
- [ ] Add "Forgot Password?"-link (optional)
