### ISSUE TITLE
Dashboard page

### ISSUE THREAD

**Issue by manusmd** [manusmd/mystudy#4]
# Story
As a user
I want to see charts which sum up the most important numbers as students and teachers per subject.

# Design
![image](https://user-images.githubusercontent.com/89474622/142896135-f86a3c7b-1ab5-4118-a1ae-b160df1313a7.png)

# Components to create
_!!! Brackets contain the props !!!_

- [x] Navigation bar(unknown props)
- [x] small Chart (charttype, data I want to analyze)
- [ ] big Chart (charttype, data I want to analyze) (optional)

# Tasks
 - [x] Add page title
 - [x] Add charts
 - [ ] Add navigation bar
