### ISSUE TITLE
Students page

### ISSUE THREAD

**Issue by manusmd** [manusmd/mystudy#5]
# Story
As a user
I want to see all of my students on an overview page with the possibility to delete them. 

# Design
![image](https://user-images.githubusercontent.com/89474622/142952481-0a4c8641-2417-43ef-b44a-13c08d038582.png)

# Components to create
_!!! Brackets contain the props !!!_

- [x] searchBar (placeholder, callback)
- [x] studentElement (id, name)
- [x] resultsElement (fetchURL) _idea is to use this component for all results_ 
- [ ] addButton (without props)

# Tasks
- [x] Add page title
- [ ] Add searchBar
- [x] Add resultsElement
- [ ] Add "addButton"
