### ISSUE TITLE
Student Details Page

### ISSUE THREAD

**Issue by manusmd** [manusmd/mystudy#9]
# Story
As a user
I want to click on a student to see the details like name, address, telephone, group(s) and subject(s) of the student.

# Design
![image](https://user-images.githubusercontent.com/89474622/142998042-e340fca2-2771-481c-8a2f-4d033ef3f98a.png)

# Components to create
_!!! Brackets contain the props !!!_

- [x] thinInput(placeholder, callback)
- [ ] mapElement(location)
- [ ] studentTeacherForm(surname, lastName, address, phone, groups[], subjects[])

# Tasks

- [x] Add page title
- [ ] Add mapElement
- [x] Add studentTeacherForm
- [ ] Add Cancel Button
- [ ] Add Save Button
